apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: litmus-nonprivileged-binding
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/part-of: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: litmus-nonprivileged
subjects:
- kind: ServiceAccount
  name: "{{ .Values.serviceAccountNonpriv }}"
  namespace: "{{ .Release.Namespace }}"